
--criar o usuario dentro do banco de dados
--PARA DEVOPS
CREATE TABLE tbl_alerta (
    id_alerta    INTEGER GENERATED BY DEFAULT AS IDENTITY,
    tipo         VARCHAR2(50) NOT NULL,
    mensagem     VARCHAR2(500) NOT NULL,
    data_criacao TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

ALTER TABLE tbl_alerta ADD CONSTRAINT tbl_alerta_pk PRIMARY KEY ( id_alerta );

CREATE TABLE tbl_dispositivo_iot (
    id_dispositivo   INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_modulo        VARCHAR2(100) NOT NULL UNIQUE,
    mac_endereco     VARCHAR2(50) NOT NULL UNIQUE,
    projeto          VARCHAR2(100) NOT NULL,
    status           VARCHAR2(50) NOT NULL,
    id_endereco      INTEGER NOT NULL,
    data_criacao     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    data_atualizacao TIMESTAMP
);

ALTER TABLE tbl_dispositivo_iot ADD CONSTRAINT tbl_dispositivo_iot_pk PRIMARY KEY ( id_dispositivo );

CREATE TABLE tbl_endereco (
    id_endereco      INTEGER GENERATED BY DEFAULT AS IDENTITY,
    logradouro       VARCHAR2(100) NOT NULL,
    bairro           VARCHAR2(50) NOT NULL,
    complemento      VARCHAR2(100),
    uf               CHAR(2) NOT NULL,
    localidade       VARCHAR2(50) NOT NULL,
    latitude         NUMBER(10, 6),
    longitude        NUMBER(11, 6),
    data_criacao     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    data_atualizacao TIMESTAMP
);

ALTER TABLE tbl_endereco ADD CONSTRAINT tbl_endereco_pk PRIMARY KEY ( id_endereco );

CREATE TABLE tbl_leitura (
    id_leitura     INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_dispositivo INTEGER NOT NULL,
    nivel_agua_cm  NUMBER(8, 3) NOT NULL,
    status_nivel   VARCHAR2(20) NOT NULL,
    data_criacao   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    id_alerta      INTEGER NOT NULL
);

ALTER TABLE tbl_leitura ADD CONSTRAINT tbl_leitura_pk PRIMARY KEY ( id_leitura );

CREATE TABLE tbl_telefone (
    id_telefone      INTEGER GENERATED BY DEFAULT AS IDENTITY,
    ddd              CHAR(2) NOT NULL,
    numero           CHAR(9) NOT NULL,
    data_criacao     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    data_atualizacao TIMESTAMP
);

ALTER TABLE tbl_telefone ADD CONSTRAINT tbl_telefone_pk PRIMARY KEY ( id_telefone );

CREATE TABLE tbl_usuario (
    id_usuario       INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nome             VARCHAR2(70) NOT NULL,
    email            VARCHAR2(50) NOT NULL UNIQUE,
    senha            VARCHAR2(255) NOT NULL,
    id_endereco      INTEGER NOT NULL,
    id_telefone      INTEGER NOT NULL,
    data_criacao     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    data_atualizacao TIMESTAMP
);

ALTER TABLE tbl_usuario ADD CONSTRAINT tbl_usuario_pk PRIMARY KEY ( id_usuario );

ALTER TABLE tbl_dispositivo_iot
    ADD CONSTRAINT tbl_disp_endereco_fk FOREIGN KEY ( id_endereco )
        REFERENCES tbl_endereco ( id_endereco );

ALTER TABLE tbl_leitura
    ADD CONSTRAINT tbl_leitura_tbl_alerta_fk FOREIGN KEY ( id_alerta )
        REFERENCES tbl_alerta ( id_alerta );

ALTER TABLE tbl_leitura
    ADD CONSTRAINT tbl_leitura_disp_fk FOREIGN KEY ( id_dispositivo )
        REFERENCES tbl_dispositivo_iot ( id_dispositivo );

ALTER TABLE tbl_usuario
    ADD CONSTRAINT tbl_usuario_tbl_endereco_fk FOREIGN KEY ( id_endereco )
        REFERENCES tbl_endereco ( id_endereco );

ALTER TABLE tbl_usuario
    ADD CONSTRAINT tbl_usuario_tbl_telefone_fk FOREIGN KEY ( id_telefone )
        REFERENCES tbl_telefone ( id_telefone );