-- Criar o usuário FIAP com tablespace padrão e quota
--PARA A MATERIA DE DEVOPS
ALTER SESSION SET CONTAINER = XEPDB1;
CREATE USER fiap IDENTIFIED BY Fiap123456 DEFAULT TABLESPACE users TEMPORARY TABLESPACE temp;
GRANT CONNECT, RESOURCE TO fiap;
ALTER USER fiap QUOTA UNLIMITED ON users;